### PR TITLE
Potential update to your repo

### PR DESCRIPTION
**Pull request by gellings**
Hey Seth, I don't want to be to pushy with this stuff but I was trying to help you get up and going a little faster.  Since we been changing stuff so much I wanted to show you a working demo.  Forgive me if these instructions are to basic, I just want to be clear.  If you want to see what I'm talking about and decide if you want to merge, then try the following...
`cd ~`
`git clone https://github.com/gellings/SUAS_UC.git`
`cd SUAS_UC/SUAS_ws`
`git submodule update --init --recursive`
`catkin_make`
`source devel/setup.bash`
`roslaunch rosplane_sim fixedwing.launch`

I hope this is helpful.  Let me know if you have problems.

### CODE REVIEW

**Comment by sethholsinger** [comment]
Hey thanks I didn't see your post as this repositories location was changed. I will checkout the branch you want to merge. Thanks for your help.

**Comment by gellings** [comment]
I hope it helps.  I know that rosflight has been updated since I made this PR but what I sent you should still work and might be a good starting point.

**Comment by sethholsinger** [comment]
hey I am getting an error when I am trying to run the code you provided.
```
setting /run_id to f06fce56-882c-11e7-b695-74da38aefee1
process[rosout-1]: started with pid [23007]
started core service [/rosout]
process[gazebo-2]: started with pid [23031]
process[gazebo_gui-3]: started with pid [23036]
process[spawn_fixedwing-4]: started with pid [23041]
process[fixedwing/autopilot-5]: started with pid [23042]
process[fixedwing/estimator-6]: started with pid [23043]
process[fixedwing/status_publisher-7]: started with pid [23053]
process[fixedwing/pathfollower-8]: started with pid [23070]
process[fixedwing/pathmanager-9]: started with pid [23077]
process[fixedwing/pathplanner-10]: started with pid [23080]
SpawnModel script started
[gazebo-2] process has died [pid 23031, exit code 255, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -u -e ode worlds/empty.world __name:=gazebo __log:=/home/risc-pc2/.ros/log/f06fce56-882c-11e7-b695-74da38aefee1/gazebo-2.log].
log file: /home/risc-pc2/.ros/log/f06fce56-882c-11e7-b695-74da38aefee1/gazebo-2*.log
publishing and latching message. Press ctrl-C to terminate
[INFO] [1503511226.121343, 0.000000]: Loading model XML from ros parameter
[INFO] [1503511226.122362, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
```
Any idea what this means. It worked the first time I tried to run it.

**Comment by gellings** [comment]
I'm not sure. I think its a Gazebo problem.  I recommend using at least ROS Kinetic/ubuntu 16.04 because they have improved gazebo (I think it jumps from v2 to v7).  You can also try running gazebo once without ROS and closing it and trying again.  It sometimes works for me if gazebo is crashing.

**Comment by sethholsinger** [comment]
So I figured out the issue there was a background gazebo process that was running and preventing the simulation from launching. The only other issue I have encountered is that simulation time will not advance.

**Comment by gellings** [comment]
I think it starts up paused, so you will have to push play (bottom of the gazebo gui).

**Comment by sethholsinger** [comment]
I tried that it before and it didn't work. I just tried it again now and it worked. Not sure why, but it is fully working now. Thanks.

**Comment by gellings** [comment]
You can now find a similar setup at github.com/byu-uav-class/rosflight_ws

**Pull request closed without merging**
